name: UHI_predictor
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pandas
  - matplotlib
  - numpy
  - geopandas
  - scipy
  - seaborn
  - openpyxl
  - datetime
  - folium
  - ipython
  - branca
  - pip